# Generated by Django 5.0.2 on 2024-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
